LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := harbour
LOCAL_CFLAGS := -Werror -DHB_HAS_PCRE -DHAVE_CONFIG_H -DHB_MT_VM

HARBOUR_PRG_FILES := ../obj/harbinit.c \
   ../obj/dbstrux.c \
   ../obj/rddsys.c \
   ../obj/rddord.c \
   ../obj/adir.c \
   ../obj/errsys.c \
   ../obj/hbfilehi.c \
   ../obj/hbini.c \
   ../obj/memvarhb.c \
   ../obj/objfunc.c \
   ../obj/tclass.c \
   ../obj/tobject.c \
   ../obj/valtoexp.c \
   ../obj/sxcompat.c \
   ../obj/sxtrig.c \
   \
   ../obj/cgi.c \
   ../obj/client.c \
   ../obj/encb64.c \
   ../obj/encoder.c \
   ../obj/encqp.c \
   ../obj/encurl.c \
   ../obj/ftpcli.c \
   ../obj/httpcli.c \
   ../obj/log.c \
   ../obj/sessid.c \
   ../obj/thtml.c \
   ../obj/url.c

LOCAL_SRC_FILES  := $(HARBOUR_PRG_FILES) \
   \
   $(HARBOUR_DIR)/src/codepage/big5.c \
   $(HARBOUR_DIR)/src/codepage/cp_utf8.c \
   $(HARBOUR_DIR)/src/codepage/cpbg866.c \
   $(HARBOUR_DIR)/src/codepage/cpbgmik.c \
   $(HARBOUR_DIR)/src/codepage/cpbgwin.c \
   $(HARBOUR_DIR)/src/codepage/cpcs852.c \
   $(HARBOUR_DIR)/src/codepage/cpcskamc.c \
   $(HARBOUR_DIR)/src/codepage/cpcswin.c \
   $(HARBOUR_DIR)/src/codepage/cpde850.c \
   $(HARBOUR_DIR)/src/codepage/cpdeiso.c \
   $(HARBOUR_DIR)/src/codepage/cpdewin.c \
   $(HARBOUR_DIR)/src/codepage/cpdk865.c \
   $(HARBOUR_DIR)/src/codepage/cpel437.c \
   $(HARBOUR_DIR)/src/codepage/cpelwin.c \
   $(HARBOUR_DIR)/src/codepage/cpes850.c \
   $(HARBOUR_DIR)/src/codepage/cpeswin.c \
   $(HARBOUR_DIR)/src/codepage/cpfi850.c \
   $(HARBOUR_DIR)/src/codepage/cpfr850.c \
   $(HARBOUR_DIR)/src/codepage/cpfrwin.c \
   $(HARBOUR_DIR)/src/codepage/cphe862.c \
   $(HARBOUR_DIR)/src/codepage/cphewin.c \
   $(HARBOUR_DIR)/src/codepage/cphr852.c \
   $(HARBOUR_DIR)/src/codepage/cphrwin.c \
   $(HARBOUR_DIR)/src/codepage/cphu852.c \
   $(HARBOUR_DIR)/src/codepage/cphuwin.c \
   $(HARBOUR_DIR)/src/codepage/cpit437.c \
   $(HARBOUR_DIR)/src/codepage/cpit850.c \
   $(HARBOUR_DIR)/src/codepage/cpitwin.c \
   $(HARBOUR_DIR)/src/codepage/cplt775.c \
   $(HARBOUR_DIR)/src/codepage/cpltwin.c \
   $(HARBOUR_DIR)/src/codepage/cpnl850.c \
   $(HARBOUR_DIR)/src/codepage/cpno865.c \
   $(HARBOUR_DIR)/src/codepage/cppl852.c \
   $(HARBOUR_DIR)/src/codepage/cpplmaz.c \
   $(HARBOUR_DIR)/src/codepage/cpplwin.c \
   $(HARBOUR_DIR)/src/codepage/cppt850.c \
   $(HARBOUR_DIR)/src/codepage/cpptiso.c \
   $(HARBOUR_DIR)/src/codepage/cpro852.c \
   $(HARBOUR_DIR)/src/codepage/cprowin.c \
   $(HARBOUR_DIR)/src/codepage/cpru1251.c \
   $(HARBOUR_DIR)/src/codepage/cpru866.c \
   $(HARBOUR_DIR)/src/codepage/cprukoi8.c \
   $(HARBOUR_DIR)/src/codepage/cpsk852.c \
   $(HARBOUR_DIR)/src/codepage/cpskkamc.c \
   $(HARBOUR_DIR)/src/codepage/cpskwin.c \
   $(HARBOUR_DIR)/src/codepage/cpsr646.c \
   $(HARBOUR_DIR)/src/codepage/cpsrwin.c \
   $(HARBOUR_DIR)/src/codepage/cptriso.c \
   $(HARBOUR_DIR)/src/codepage/cptrwin.c \
   $(HARBOUR_DIR)/src/codepage/cpua1251.c \
   $(HARBOUR_DIR)/src/codepage/cpua866.c \
   $(HARBOUR_DIR)/src/codepage/cpuakoi8.c \
   $(HARBOUR_DIR)/src/codepage/uc1125.c \
   $(HARBOUR_DIR)/src/codepage/uc1250.c \
   $(HARBOUR_DIR)/src/codepage/uc1251.c \
   $(HARBOUR_DIR)/src/codepage/uc1252.c \
   $(HARBOUR_DIR)/src/codepage/uc1253.c \
   $(HARBOUR_DIR)/src/codepage/uc1254.c \
   $(HARBOUR_DIR)/src/codepage/uc1255.c \
   $(HARBOUR_DIR)/src/codepage/uc1257.c \
   $(HARBOUR_DIR)/src/codepage/uc646_yu.c \
   $(HARBOUR_DIR)/src/codepage/uc646yuc.c \
   $(HARBOUR_DIR)/src/codepage/uc737.c \
   $(HARBOUR_DIR)/src/codepage/uc775.c \
   $(HARBOUR_DIR)/src/codepage/uc850.c \
   $(HARBOUR_DIR)/src/codepage/uc852.c \
   $(HARBOUR_DIR)/src/codepage/uc855.c \
   $(HARBOUR_DIR)/src/codepage/uc860.c \
   $(HARBOUR_DIR)/src/codepage/uc861.c \
   $(HARBOUR_DIR)/src/codepage/uc862.c \
   $(HARBOUR_DIR)/src/codepage/uc865.c \
   $(HARBOUR_DIR)/src/codepage/uc866.c \
   $(HARBOUR_DIR)/src/codepage/uc8859_1.c \
   $(HARBOUR_DIR)/src/codepage/uc8859_2.c \
   $(HARBOUR_DIR)/src/codepage/uc8859_5.c \
   $(HARBOUR_DIR)/src/codepage/uc8859_6.c \
   $(HARBOUR_DIR)/src/codepage/uc8859_9.c \
   $(HARBOUR_DIR)/src/codepage/uckam.c \
   $(HARBOUR_DIR)/src/codepage/uckoi8.c \
   $(HARBOUR_DIR)/src/codepage/uckoi8u.c \
   $(HARBOUR_DIR)/src/codepage/ucmaz.c \
   $(HARBOUR_DIR)/src/codepage/ucmik.c \
   $(HARBOUR_DIR)/src/codepage/uc500.c \
   $(HARBOUR_DIR)/src/codepage/uc856.c \
   $(HARBOUR_DIR)/src/codepage/uc875.c \
   \
   $(HARBOUR_DIR)/src/common/expropt1.c \
   $(HARBOUR_DIR)/src/common/expropt2.c \
   $(HARBOUR_DIR)/src/common/funcid.c \
   $(HARBOUR_DIR)/src/common/hbarch.c \
   $(HARBOUR_DIR)/src/common/hbdate.c \
   $(HARBOUR_DIR)/src/common/hbffind.c \
   $(HARBOUR_DIR)/src/common/hbfopen.c \
   $(HARBOUR_DIR)/src/common/hbfsapi.c \
   $(HARBOUR_DIR)/src/common/hbgete.c \
   $(HARBOUR_DIR)/src/common/hbhash.c \
   $(HARBOUR_DIR)/src/common/hbmem.c \
   $(HARBOUR_DIR)/src/common/hbprintf.c \
   $(HARBOUR_DIR)/src/common/hbstr.c \
   $(HARBOUR_DIR)/src/common/hbstrbm.c \
   $(HARBOUR_DIR)/src/common/hbtrace.c \
   $(HARBOUR_DIR)/src/common/hbver.c \
   $(HARBOUR_DIR)/src/common/hbverdsp.c \
   $(HARBOUR_DIR)/src/common/hbwin.c \
   $(HARBOUR_DIR)/src/common/strwild.c \
   \
   $(HARBOUR_DIR)/src/compiler/cmdcheck.c \
   $(HARBOUR_DIR)/src/compiler/compi18n.c \
   $(HARBOUR_DIR)/src/compiler/complex.c \
   $(HARBOUR_DIR)/src/compiler/expropta.c \
   $(HARBOUR_DIR)/src/compiler/exproptb.c \
   $(HARBOUR_DIR)/src/compiler/genc.c \
   $(HARBOUR_DIR)/src/compiler/gencc.c \
   $(HARBOUR_DIR)/src/compiler/genhrb.c \
   $(HARBOUR_DIR)/src/compiler/hbcmplib.c \
   $(HARBOUR_DIR)/src/compiler/hbcomp.c \
   $(HARBOUR_DIR)/src/compiler/hbdbginf.c \
   $(HARBOUR_DIR)/src/compiler/hbdead.c \
   $(HARBOUR_DIR)/src/compiler/hbfix.c \
   $(HARBOUR_DIR)/src/compiler/hbfunchk.c \
   $(HARBOUR_DIR)/src/compiler/hbgenerr.c \
   $(HARBOUR_DIR)/src/compiler/hbident.c \
   $(HARBOUR_DIR)/src/compiler/hblbl.c \
   $(HARBOUR_DIR)/src/compiler/hbmain.c \
   $(HARBOUR_DIR)/src/compiler/hbopt.c \
   $(HARBOUR_DIR)/src/compiler/hbpcode.c \
   $(HARBOUR_DIR)/src/compiler/hbstripl.c \
   $(HARBOUR_DIR)/src/compiler/hbusage.c \
   $(HARBOUR_DIR)/src/compiler/ppcomp.c \
   $(HARBOUR_DIR)/src/compiler/harboury.c \
   $(HARBOUR_DIR)/src/debug/dbgentry.c \
   \
   $(HARBOUR_DIR)/src/lang/l_be.c \
   $(HARBOUR_DIR)/src/lang/l_bg.c \
   $(HARBOUR_DIR)/src/lang/l_ca.c \
   $(HARBOUR_DIR)/src/lang/l_cs.c \
   $(HARBOUR_DIR)/src/lang/l_de.c \
   $(HARBOUR_DIR)/src/lang/l_el.c \
   $(HARBOUR_DIR)/src/lang/l_eo.c \
   $(HARBOUR_DIR)/src/lang/l_es_419.c \
   $(HARBOUR_DIR)/src/lang/l_es.c \
   $(HARBOUR_DIR)/src/lang/l_eu.c \
   $(HARBOUR_DIR)/src/lang/l_fr.c \
   $(HARBOUR_DIR)/src/lang/l_gl.c \
   $(HARBOUR_DIR)/src/lang/l_he.c \
   $(HARBOUR_DIR)/src/lang/l_hr.c \
   $(HARBOUR_DIR)/src/lang/l_hu.c \
   $(HARBOUR_DIR)/src/lang/l_id.c \
   $(HARBOUR_DIR)/src/lang/l_is.c \
   $(HARBOUR_DIR)/src/lang/l_it.c \
   $(HARBOUR_DIR)/src/lang/l_ko.c \
   $(HARBOUR_DIR)/src/lang/l_lt.c \
   $(HARBOUR_DIR)/src/lang/l_nl.c \
   $(HARBOUR_DIR)/src/lang/l_pl.c \
   $(HARBOUR_DIR)/src/lang/l_pt_br.c \
   $(HARBOUR_DIR)/src/lang/l_pt.c \
   $(HARBOUR_DIR)/src/lang/l_ro.c \
   $(HARBOUR_DIR)/src/lang/l_ru.c \
   $(HARBOUR_DIR)/src/lang/l_sk.c \
   $(HARBOUR_DIR)/src/lang/l_sl.c \
   $(HARBOUR_DIR)/src/lang/l_sr_cyr.c\
   $(HARBOUR_DIR)/src/lang/l_sr_lat.c \
   $(HARBOUR_DIR)/src/lang/l_sv.c \
   $(HARBOUR_DIR)/src/lang/l_tr.c \
   $(HARBOUR_DIR)/src/lang/l_uk.c \
   $(HARBOUR_DIR)/src/lang/l_zh_sim.c \
   $(HARBOUR_DIR)/src/lang/l_zh.c \
   \
   $(HARBOUR_DIR)/src/macro/macroa.c \
   $(HARBOUR_DIR)/src/macro/macrob.c \
   $(HARBOUR_DIR)/src/macro/macrolex.c \
   $(HARBOUR_DIR)/src/macro/macroy.c \
   \
   $(HARBOUR_DIR)/src/pp/ppcore.c \
   $(HARBOUR_DIR)/src/pp/pplib.c \
   $(HARBOUR_DIR)/src/pp/pplib2.c \
   $(HARBOUR_DIR)/src/pp/pptable.c \
   \
   $(HARBOUR_DIR)/src/rdd/dbcmd.c \
   $(HARBOUR_DIR)/src/rdd/dbcmd53.c \
   $(HARBOUR_DIR)/src/rdd/dbcmdhb.c \
   $(HARBOUR_DIR)/src/rdd/dbdetach.c \
   $(HARBOUR_DIR)/src/rdd/dbdrop.c \
   $(HARBOUR_DIR)/src/rdd/dbexists.c \
   $(HARBOUR_DIR)/src/rdd/dbfcdx/dbfcdx1.c \
   $(HARBOUR_DIR)/src/rdd/dbfcdx/sixcdx1.c \
   $(HARBOUR_DIR)/src/rdd/dbffpt/dbffpt1.c \
   $(HARBOUR_DIR)/src/rdd/dbfntx/dbfntx1.c \
   $(HARBOUR_DIR)/src/rdd/hbsix/sxcompr.c \
   $(HARBOUR_DIR)/src/rdd/hbsix/sxcrypt.c \
   $(HARBOUR_DIR)/src/rdd/hbsix/sxdate.c \
   $(HARBOUR_DIR)/src/rdd/hbsix/sxfname.c \
   $(HARBOUR_DIR)/src/rdd/hbsix/sxord.c \
   $(HARBOUR_DIR)/src/rdd/hbsix/sxredir.c \
   $(HARBOUR_DIR)/src/rdd/hbsix/sxsem.c \
   $(HARBOUR_DIR)/src/rdd/hbsix/sxtable.c \
   $(HARBOUR_DIR)/src/rdd/hbsix/sxutil.c \
   $(HARBOUR_DIR)/src/rdd/dbf1.c \
   $(HARBOUR_DIR)/src/rdd/dbrename.c \
   $(HARBOUR_DIR)/src/rdd/dbsql.c \
   $(HARBOUR_DIR)/src/rdd/delim1.c \
   $(HARBOUR_DIR)/src/rdd/fieldhb.c \
   $(HARBOUR_DIR)/src/rdd/ordcount.c \
   $(HARBOUR_DIR)/src/rdd/ordwldsk.c \
   $(HARBOUR_DIR)/src/rdd/rddinfo.c \
   $(HARBOUR_DIR)/src/rdd/sdf1.c \
   $(HARBOUR_DIR)/src/rdd/wacore.c \
   $(HARBOUR_DIR)/src/rdd/wafunc.c \
   $(HARBOUR_DIR)/src/rdd/workarea.c \
   \
   $(HARBOUR_DIR)/src/rtl/abs.c \
   $(HARBOUR_DIR)/src/rtl/accept.c \
   $(HARBOUR_DIR)/src/rtl/ampm.c \
   $(HARBOUR_DIR)/src/rtl/arc4.c \
   $(HARBOUR_DIR)/src/rtl/at.c \
   $(HARBOUR_DIR)/src/rtl/ati.c \
   $(HARBOUR_DIR)/src/rtl/base64c.c \
   $(HARBOUR_DIR)/src/rtl/base64d.c \
   $(HARBOUR_DIR)/src/rtl/binnum.c \
   $(HARBOUR_DIR)/src/rtl/box.c \
   $(HARBOUR_DIR)/src/rtl/cdpapi.c \
   $(HARBOUR_DIR)/src/rtl/cdpapihb.c \
   $(HARBOUR_DIR)/src/rtl/cdpbox.c \
   $(HARBOUR_DIR)/src/rtl/chrasc.c \
   $(HARBOUR_DIR)/src/rtl/chruni.c \
   $(HARBOUR_DIR)/src/rtl/colorind.c \
   $(HARBOUR_DIR)/src/rtl/console.c \
   $(HARBOUR_DIR)/src/rtl/copyfile.c \
   $(HARBOUR_DIR)/src/rtl/cputime.c \
   $(HARBOUR_DIR)/src/rtl/datec.c \
   $(HARBOUR_DIR)/src/rtl/dates.c \
   $(HARBOUR_DIR)/src/rtl/dateshb.c \
   $(HARBOUR_DIR)/src/rtl/datesx.c \
   $(HARBOUR_DIR)/src/rtl/defpath.c \
   $(HARBOUR_DIR)/src/rtl/defpathu.c \
   $(HARBOUR_DIR)/src/rtl/descend.c \
   $(HARBOUR_DIR)/src/rtl/dirdrive.c \
   $(HARBOUR_DIR)/src/rtl/direct.c \
   $(HARBOUR_DIR)/src/rtl/diskspac.c \
   $(HARBOUR_DIR)/src/rtl/disksphb.c \
   $(HARBOUR_DIR)/src/rtl/do.c \
   $(HARBOUR_DIR)/src/rtl/empty.c \
   $(HARBOUR_DIR)/src/rtl/errapi.c \
   $(HARBOUR_DIR)/src/rtl/errapiu.c \
   $(HARBOUR_DIR)/src/rtl/errint.c \
   $(HARBOUR_DIR)/src/rtl/errintlo.c \
   $(HARBOUR_DIR)/src/rtl/file.c \
   $(HARBOUR_DIR)/src/rtl/filebuf.c \
   $(HARBOUR_DIR)/src/rtl/filehb.c \
   $(HARBOUR_DIR)/src/rtl/filesys.c \
   $(HARBOUR_DIR)/src/rtl/fkmax.c \
   $(HARBOUR_DIR)/src/rtl/fmhb.c \
   $(HARBOUR_DIR)/src/rtl/fnsplit.c \
   $(HARBOUR_DIR)/src/rtl/fscopy.c \
   $(HARBOUR_DIR)/src/rtl/fserr.c \
   $(HARBOUR_DIR)/src/rtl/fslink.c \
   $(HARBOUR_DIR)/src/rtl/fssize.c \
   $(HARBOUR_DIR)/src/rtl/fstemp.c \
   $(HARBOUR_DIR)/src/rtl/gete.c \
   $(HARBOUR_DIR)/src/rtl/gt.c \
   $(HARBOUR_DIR)/src/rtl/gtapi.c \
   $(HARBOUR_DIR)/src/rtl/gtapiu.c \
   $(HARBOUR_DIR)/src/rtl/gtchrmap.c \
   $(HARBOUR_DIR)/src/rtl/gtclip.c \
   $(HARBOUR_DIR)/src/rtl/gtfunc.c \
   $(HARBOUR_DIR)/src/rtl/gtkbstat.c \
   $(HARBOUR_DIR)/src/rtl/gtkeycod.c \
   $(HARBOUR_DIR)/src/rtl/gtsys.c \
   $(HARBOUR_DIR)/src/rtl/gttone.c \
   $(HARBOUR_DIR)/src/rtl/gx.c \
   $(HARBOUR_DIR)/src/rtl/hardcr.c \
   $(HARBOUR_DIR)/src/rtl/hbadler.c \
   $(HARBOUR_DIR)/src/rtl/hbascii.c \
   $(HARBOUR_DIR)/src/rtl/hbbffnc.c \
   $(HARBOUR_DIR)/src/rtl/hbbfish.c \
   $(HARBOUR_DIR)/src/rtl/hbbit.c \
   $(HARBOUR_DIR)/src/rtl/hbbyte.c \
   $(HARBOUR_DIR)/src/rtl/hbcom.c \
   $(HARBOUR_DIR)/src/rtl/hbcomhb.c \
   $(HARBOUR_DIR)/src/rtl/hbcrc.c \
   $(HARBOUR_DIR)/src/rtl/hbdef.c \
   $(HARBOUR_DIR)/src/rtl/hbdyn.c \
   $(HARBOUR_DIR)/src/rtl/hbdynhb.c \
   $(HARBOUR_DIR)/src/rtl/hbfeof.c \
   $(HARBOUR_DIR)/src/rtl/hbfile.c \
   $(HARBOUR_DIR)/src/rtl/hbfilehc.c \
   $(HARBOUR_DIR)/src/rtl/hbgtcore.c \
   $(HARBOUR_DIR)/src/rtl/hbhex.c \
   $(HARBOUR_DIR)/src/rtl/hbi18n1.c \
   $(HARBOUR_DIR)/src/rtl/hbinet.c \
   $(HARBOUR_DIR)/src/rtl/hbjson.c \
   $(HARBOUR_DIR)/src/rtl/hblpp.c \
   $(HARBOUR_DIR)/src/rtl/hblpphb.c \
   $(HARBOUR_DIR)/src/rtl/hbmd5.c \
   $(HARBOUR_DIR)/src/rtl/hbmd5enc.c \
   $(HARBOUR_DIR)/src/rtl/hbntos.c \
   $(HARBOUR_DIR)/src/rtl/hbproces.c \
   $(HARBOUR_DIR)/src/rtl/hbprocfn.c \
   $(HARBOUR_DIR)/src/rtl/hbrand.c \
   $(HARBOUR_DIR)/src/rtl/hbrandom.c \
   $(HARBOUR_DIR)/src/rtl/hbregex.c \
   $(HARBOUR_DIR)/src/rtl/hbregexc.c \
   $(HARBOUR_DIR)/src/rtl/hbrunfun.c \
   $(HARBOUR_DIR)/src/rtl/hbsha1.c \
   $(HARBOUR_DIR)/src/rtl/hbsha1hm.c \
   $(HARBOUR_DIR)/src/rtl/hbsha2.c \
   $(HARBOUR_DIR)/src/rtl/hbsha2hm.c \
   $(HARBOUR_DIR)/src/rtl/hbsocket.c \
   $(HARBOUR_DIR)/src/rtl/hbsockhb.c \
   $(HARBOUR_DIR)/src/rtl/hbstrfmt.c \
   $(HARBOUR_DIR)/src/rtl/hbstrsh.c \
   $(HARBOUR_DIR)/src/rtl/hbtoken.c \
   $(HARBOUR_DIR)/src/rtl/hbzlib.c \
   $(HARBOUR_DIR)/src/rtl/hbzlibc.c \
   $(HARBOUR_DIR)/src/rtl/hbzlibgz.c \
   $(HARBOUR_DIR)/src/rtl/hbznet.c \
   $(HARBOUR_DIR)/src/rtl/idle.c \
   $(HARBOUR_DIR)/src/rtl/inkey.c \
   $(HARBOUR_DIR)/src/rtl/inkeyapi.c \
   $(HARBOUR_DIR)/src/rtl/is.c \
   $(HARBOUR_DIR)/src/rtl/isprint.c \
   $(HARBOUR_DIR)/src/rtl/itemseri.c \
   $(HARBOUR_DIR)/src/rtl/lang.c \
   $(HARBOUR_DIR)/src/rtl/langapi.c \
   $(HARBOUR_DIR)/src/rtl/left.c \
   $(HARBOUR_DIR)/src/rtl/len.c \
   $(HARBOUR_DIR)/src/rtl/lennum.c \
   $(HARBOUR_DIR)/src/rtl/libnamec.c \
   $(HARBOUR_DIR)/src/rtl/math.c \
   $(HARBOUR_DIR)/src/rtl/maxrow.c \
   $(HARBOUR_DIR)/src/rtl/memofile.c \
   $(HARBOUR_DIR)/src/rtl/minmax.c \
   $(HARBOUR_DIR)/src/rtl/mlcfunc.c \
   $(HARBOUR_DIR)/src/rtl/mod.c \
   $(HARBOUR_DIR)/src/rtl/mouse53.c \
   $(HARBOUR_DIR)/src/rtl/mouseapi.c \
   $(HARBOUR_DIR)/src/rtl/mousehb.c \
   $(HARBOUR_DIR)/src/rtl/mtran.c \
   $(HARBOUR_DIR)/src/rtl/natmsg.c \
   $(HARBOUR_DIR)/src/rtl/natmsgu.c \
   $(HARBOUR_DIR)/src/rtl/net.c \
   $(HARBOUR_DIR)/src/rtl/oemansi.c \
   $(HARBOUR_DIR)/src/rtl/oldbox.c \
   $(HARBOUR_DIR)/src/rtl/oldclear.c \
   $(HARBOUR_DIR)/src/rtl/pad.c \
   $(HARBOUR_DIR)/src/rtl/padx.c \
   $(HARBOUR_DIR)/src/rtl/philes.c \
   $(HARBOUR_DIR)/src/rtl/philes53.c \
   $(HARBOUR_DIR)/src/rtl/rat.c \
   $(HARBOUR_DIR)/src/rtl/replic.c \
   $(HARBOUR_DIR)/src/rtl/right.c \
   $(HARBOUR_DIR)/src/rtl/round.c \
   $(HARBOUR_DIR)/src/rtl/run.c \
   $(HARBOUR_DIR)/src/rtl/samples.c \
   $(HARBOUR_DIR)/src/rtl/saverest.c \
   $(HARBOUR_DIR)/src/rtl/scroll.c \
   $(HARBOUR_DIR)/src/rtl/scrrow.c \
   $(HARBOUR_DIR)/src/rtl/seconds.c \
   $(HARBOUR_DIR)/src/rtl/setcolor.c \
   $(HARBOUR_DIR)/src/rtl/setcurs.c \
   $(HARBOUR_DIR)/src/rtl/setkey.c \
   $(HARBOUR_DIR)/src/rtl/setpos.c \
   $(HARBOUR_DIR)/src/rtl/setposbs.c \
   $(HARBOUR_DIR)/src/rtl/sha1.c \
   $(HARBOUR_DIR)/src/rtl/sha1hmac.c \
   $(HARBOUR_DIR)/src/rtl/sha2.c \
   $(HARBOUR_DIR)/src/rtl/sha2hmac.c \
   $(HARBOUR_DIR)/src/rtl/shadow.c \
   $(HARBOUR_DIR)/src/rtl/shadowu.c \
   $(HARBOUR_DIR)/src/rtl/soundex.c \
   $(HARBOUR_DIR)/src/rtl/space.c \
   $(HARBOUR_DIR)/src/rtl/spfiles.c \
   $(HARBOUR_DIR)/src/rtl/str.c \
   $(HARBOUR_DIR)/src/rtl/strc.c \
   $(HARBOUR_DIR)/src/rtl/strcase.c \
   $(HARBOUR_DIR)/src/rtl/strclear.c \
   $(HARBOUR_DIR)/src/rtl/strmatch.c \
   $(HARBOUR_DIR)/src/rtl/strrepl.c \
   $(HARBOUR_DIR)/src/rtl/strtoexp.c \
   $(HARBOUR_DIR)/src/rtl/strtran.c \
   $(HARBOUR_DIR)/src/rtl/strxor.c \
   $(HARBOUR_DIR)/src/rtl/strzero.c \
   $(HARBOUR_DIR)/src/rtl/stuff.c \
   $(HARBOUR_DIR)/src/rtl/substr.c \
   $(HARBOUR_DIR)/src/rtl/tone.c \
   $(HARBOUR_DIR)/src/rtl/trace.c \
   $(HARBOUR_DIR)/src/rtl/transfrm.c \
   $(HARBOUR_DIR)/src/rtl/trim.c \
   $(HARBOUR_DIR)/src/rtl/type.c \
   $(HARBOUR_DIR)/src/rtl/val.c \
   $(HARBOUR_DIR)/src/rtl/valtostr.c \
   $(HARBOUR_DIR)/src/rtl/valtype.c \
   $(HARBOUR_DIR)/src/rtl/version.c \
   $(HARBOUR_DIR)/src/rtl/vfile.c \
   $(HARBOUR_DIR)/src/rtl/word.c \
   $(HARBOUR_DIR)/src/rtl/xhelp.c \
   $(HARBOUR_DIR)/src/rtl/xsavescr.c \
   $(HARBOUR_DIR)/src/rtl/gttrm/gttrm.c \
   \
   $(HARBOUR_DIR)/src/vm/arrays.c \
   $(HARBOUR_DIR)/src/vm/arrayshb.c \
   $(HARBOUR_DIR)/src/vm/asort.c \
   $(HARBOUR_DIR)/src/vm/break.c \
   $(HARBOUR_DIR)/src/vm/classes.c \
   $(HARBOUR_DIR)/src/vm/cmdarg.c \
   $(HARBOUR_DIR)/src/vm/codebloc.c \
   $(HARBOUR_DIR)/src/vm/debug.c \
   $(HARBOUR_DIR)/src/vm/dynlibhb.c \
   $(HARBOUR_DIR)/src/vm/dynsym.c \
   $(HARBOUR_DIR)/src/vm/estack.c \
   $(HARBOUR_DIR)/src/vm/eval.c \
   $(HARBOUR_DIR)/src/vm/evalhb.c \
   $(HARBOUR_DIR)/src/vm/extend.c \
   $(HARBOUR_DIR)/src/vm/extrap.c \
   $(HARBOUR_DIR)/src/vm/fm.c \
   $(HARBOUR_DIR)/src/vm/garbage.c \
   $(HARBOUR_DIR)/src/vm/hashes.c \
   $(HARBOUR_DIR)/src/vm/hashfunc.c \
   $(HARBOUR_DIR)/src/vm/hvm.c \
   $(HARBOUR_DIR)/src/vm/initexit.c \
   $(HARBOUR_DIR)/src/vm/initsymb.c \
   $(HARBOUR_DIR)/src/vm/itemapi.c \
   $(HARBOUR_DIR)/src/vm/macro.c \
   $(HARBOUR_DIR)/src/vm/memvars.c \
   $(HARBOUR_DIR)/src/vm/memvclip.c \
   $(HARBOUR_DIR)/src/vm/pbyref.c \
   $(HARBOUR_DIR)/src/vm/pcount.c \
   $(HARBOUR_DIR)/src/vm/proc.c \
   $(HARBOUR_DIR)/src/vm/procaddr.c \
   $(HARBOUR_DIR)/src/vm/pvalue.c \
   $(HARBOUR_DIR)/src/vm/pvaluehb.c \
   $(HARBOUR_DIR)/src/vm/runner.c \
   $(HARBOUR_DIR)/src/vm/set.c \
   $(HARBOUR_DIR)/src/vm/strapi.c \
   $(HARBOUR_DIR)/src/vm/thread.c \
   $(HARBOUR_DIR)/src/vm/vm.c \
   \
   $(HARBOUR_DIR)/src/3rd/pcre/chartabs.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcrebyte.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcrecomp.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcreconf.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcredfa.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcreexec.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcrefinf.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcreget.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcreglob.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcrejitc.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcremktb.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcrenewl.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcreoutf.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcrerefc.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcrestud.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcretabs.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcreucd.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcrever.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcrevutf.c \
   $(HARBOUR_DIR)/src/3rd/pcre/pcrexcls.c \
   \
   $(HARBOUR_DIR)/src/3rd/zlib/adler32.c \
   $(HARBOUR_DIR)/src/3rd/zlib/compress.c \
   $(HARBOUR_DIR)/src/3rd/zlib/crc32.c \
   $(HARBOUR_DIR)/src/3rd/zlib/deflate.c \
   $(HARBOUR_DIR)/src/3rd/zlib/gzclose.c \
   $(HARBOUR_DIR)/src/3rd/zlib/gzlib.c \
   $(HARBOUR_DIR)/src/3rd/zlib/gzread.c \
   $(HARBOUR_DIR)/src/3rd/zlib/gzwrite.c \
   $(HARBOUR_DIR)/src/3rd/zlib/infback.c \
   $(HARBOUR_DIR)/src/3rd/zlib/inffast.c \
   $(HARBOUR_DIR)/src/3rd/zlib/inflate.c \
   $(HARBOUR_DIR)/src/3rd/zlib/inftrees.c \
   $(HARBOUR_DIR)/src/3rd/zlib/trees.c \
   $(HARBOUR_DIR)/src/3rd/zlib/uncompr.c \
   $(HARBOUR_DIR)/src/3rd/zlib/zutil.c \
   \
   $(HARBOUR_DIR)/hbnetio/netiocli.c \
   \
   $(HARBOUR_DIR)/hbtip/encurlc.c \
   $(HARBOUR_DIR)/hbtip/mime.c \
   $(HARBOUR_DIR)/hbtip/misc.c
                                   
LOCAL_C_INCLUDES += $(HARBOUR_INC)/include \
   $(HARBOUR_INC)/src/compiler \
   $(HARBOUR_INC)/src/macro \
   $(HARBOUR_INC)/src/codepage \
   $(HARBOUR_INC)/src/3rd/pcre \
   $(HARBOUR_INC)/hbnetio \
   $(HARBOUR_INC)/hbtip \
   $(HARBOUR_INC)/hbssl \
   $(NDK_HOME)\platforms\$(NDK_PLATFORM)\arch-arm\usr\include
                    
LOCAL_LDLIBS := -llog 
include $(BUILD_SHARED_LIBRARY)
